config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login'
  get 'sessions/login_attempt'
  post 'sessions/login_attempt'
  get 'sessions/home'
  get 'sessions/profile'
  get 'sessions/setting'
  get 'sessions/logout'

  resources :user_groups
  resources :acc_transactions
  resources :accounts
  resources :account_types
  resources :users

  root 'home#index'
  get 'balance_sheet' => 'home#balance'












end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base

  has_many :users, :foreign_key => :group_id

end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:name, :desc)
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing user_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<h1>Listing user_groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_groups.each do |user_group| %>
      <tr>
        <td><%= user_group.name %></td>
        <td><%= user_group.desc %></td>
        <td><%= link_to 'Show', user_group %></td>
        <td><%= link_to 'Edit', edit_user_group_path(user_group) %></td>
        <td><%= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/new.html.erb
<h1>New user_group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_group.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @user_group.desc %>
</p>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>