config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login'
  get 'sessions/login_attempt'
  post 'sessions/login_attempt'
  get 'sessions/home'
  get 'sessions/profile'
  get 'sessions/setting'
  get 'sessions/logout'

  resources :user_groups
  resources :acc_transactions
  resources :accounts
  resources :account_types
  resources :users

  root 'home#index'
  get 'balance_sheet' => 'home#balance'












end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # session[:user_id] = 1
    # @current_user = User.find session[:user_id]
  end

  def balance
    @balances_sheet = Account.select("name, balance").to_a
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/balance.html.erb
<h1>Welcome XXXXXXX</h1>

<p><strong>The current balances sheet</strong></p>

<% @balances_sheet.each do |key|  %>
    Balance of account <strong><%= key.name %></strong> is : <strong><%= key.balance %></strong>
    <br>
<% end %>

<br>
<br>
<div style="width: 100%">
  <div style="width: 50%; float: left"><%= pie_chart Account.group(:name).sum(:balance) %></div>
  <div style="width: 50%; float: right"><%= column_chart Account.group(:name).sum(:balance) %></div>
</div>
<br>
<br>
<%= link_to 'Home Page', root_path %>

app/views/home/index.html.erb
<h1>Welcome <%= @current_user.name %> </h1>
<h1>Welcome <%= @current_user.id %> </h1>

<p><strong>Based on your role as a <font color="#dc143c"><%= @current_user.user_group.name %></font>, this is your dashboard:</strong></p>
<table>
  <tbody>
      <tr>
        <td><%= image_tag('manager_dashboard/view_txn.png', size: '70x70') %><br><br></td>
        <td><strong><%= link_to 'View Transactions History', acc_transactions_path %></strong><br><br></td>
      </tr>
      <tr>
        <td><%= image_tag('manager_dashboard/balance_sheet.png', size: '70x70') %><br><br></td>
        <td><strong><%= link_to 'Generate Balance Sheet', balance_sheet_path %></strong><br><br></td>
      </tr>

      <% if @current_user.user_group.name.eql? 'Manager' %>
          <tr>
            <td><%= image_tag('manager_dashboard/users.png', size: '70x70') %><br><br></td>
            <td><strong><%= link_to 'Create/Edit/Delete A User', users_path %></strong><br><br></td>
          </tr>
          <tr>
            <td><%= image_tag('manager_dashboard/accounts.png', size: '70x70') %><br><br></td>
            <td><strong><%= link_to 'Create/Edit/Delete An Account', accounts_path %></strong><br><br></td>
          </tr>
          <tr>
            <td><%= image_tag('manager_dashboard/types.png', size: '70x70') %><br><br></td>
            <td><strong><%= link_to 'Create/Edit/Delete An Account Type', account_types_path %></strong><br><br></td>
          </tr>
    <% end %>
  </tbody>
</table>

