config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login'
  get 'sessions/login_attempt'
  post 'sessions/login_attempt'
  get 'sessions/home'
  get 'sessions/profile'
  get 'sessions/setting'
  get 'sessions/logout'

  resources :user_groups
  resources :acc_transactions
  resources :accounts
  resources :account_types
  resources :users

  root 'home#index'
  get 'balance_sheet' => 'home#balance'












end

app/models/account.rb
class Account < ActiveRecord::Base
  # attr_accessor :name, :account_type_id, :balance

  belongs_to :account_type

  # has_many :from_transactions, class_name: 'Transaction', :foreign_key => :from_acc
  # has_many :to_transactions, class_name: 'Transaction', :foreign_key => :to_acc

  has_many :from_transactions, class_name: 'AccTransaction', :foreign_key => :type_a_acc
  has_many :to_transactions, class_name: 'AccTransaction', :foreign_key => :type_b_acc

  def self.update_balances(type_a, type_a_ac, type_b, type_b_ac, amount)
    acc_a = Account.find(type_a_ac)
    acc_b = Account.find(type_b_ac)

    if type_a.eql? 'from'
      acc_a.balance = acc_a.balance - amount.to_f
    else
      acc_a.balance = acc_a.balance + amount.to_f
    end
    if type_b.eql? 'from'
      acc_b.balance = acc_b.balance - amount.to_f
    else
      acc_b.balance = acc_b.balance + amount.to_f
    end

    acc_a.save
    acc_b.save
  end

  # def self.get_balance_sheet
  #   balance_sheet_details = select("name, balance")
  #   print '-----------------------------------'
  #   print balance_sheet_details
  #   print '-----------------------------------'
  #   return balance_sheet_details
  # end

end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  # attr_accessor :name, :lhs_attr, :rhs_attr, :plus_attr, :minus_attr

  has_many :accounts

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :account_type_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
    <% if @account.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

          <ul>
            <% @account.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <strong><%= f.label :name %></strong><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <!-- <%= f.label :account_type_id %><br>
    <%= f.number_field :account_type_id %>
    <br>
    <br>
    -->
      <% if @account.account_type.nil? %>
          <strong><%= f.label :account_type %></strong><br>
      <% else %>
          <p>
            <strong>Current account type:</strong>
            <%= @account.account_type.name %>
          </p>
          <strong>Change to <%= f.label :account_type %></strong><br>
      <% end %>

      <%= f.collection_select :account_type_id, AccountType.all, :id, :name %>
      <br>
      <br>
    </div>

    <div class="field">
      <%= f.label :balance %><br>
      <%= f.text_field :balance %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Account type</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.account_type.name %></td>
        <td><%= account.balance %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>
<br>
<br>
<%= link_to 'Home Page', root_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Account type:</strong>
  <%= @account.account_type.name %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>